{
  "ua": "",
  "homeUrl": "https://mozhatu.com/",
  "dcVipFlag": "true",
  "pCfgJs": "https://mozhatu.com/static/js/playerconfig.js",
  "pCfgJsR": "[\\W|\\S|.]*?MacPlayerConfig.player_list[\\W|\\S|.]*?=([\\W|\\S|.]*?),MacPlayerConfig.downer_list",
  "dcShow2Vip": {},
  "dcPlayUrl": "true",
  "cateNode": "//ul[@class='navbar-items swiper-wrapper']//a[contains(@href,'index.php/vod/type/id')]",
  "cateName": "/@title",
  "cateId": "/@href",
  "cateIdR": "//index.php/vod/type/id(\\S+).html",
  "cateManual": {
		"电影": "1",
		"连续剧": "2",
		"综艺": "3",
		"动漫": "4",
		"国产剧": "201",
		"欧美剧": "204",
		"国漫": "211",
		"日漫": "212",
        "纪录片": "5"		
	},
  "homeVodNode": "//div[@class='module-main scroll-box']/div/a",
  "homeVodName": "/@title",
  "homeVodId": "/@href",
  "homeVodIdR": "/index.php/vod/detail/id(\\S+).html",
  "homeVodImg": "/div/div[2]/img/@data-original",
  "homeVodImgR": "",
  "homeVodMark": "/div[1]/div/text()",
  "cateUrl": "https://mozhatu.com/index.php/vod/show/id/{cateId}/page/{catePg}.html",
  "cateVodNode": "//div[@class='module-items module-poster-items-base ']/a",
  "cateVodName": "/@title",
  "cateVodId": "/@href",
  "cateVodIdR": "/index.php/vod/detail/id(\\S+).html",
  "cateVodImg": "/div/div[2]/img/@data-original",
  "cateVodImgR": "",
  "cateVodMark": "/div[1]/div/text()",
  "dtUrl": "https://mozhatu.com/index.php/vod/detail/id/{vid}.html",
  "dtNode": "//div[@class='module-main']",
  "dtName": "/div[2]/div[1]/h1/text()",
  "dtNameR": "",
  "dtImg": "/div[1]/div/div/img/@data-original",
  "dtImgR": "",
  "dtCate": "/div[2]/div[1]/div/div[3]/a[1]/text()",
  "dtCateR": "",
  "dtYear": "/div[2]/div[1]/div/div[1]/a/text()",
  "dtYearR": "",
  "dtArea": "/div[2]/div[1]/div/div[2]/a/text()",
  "dtAreaR": "",
  "dtMark": "/div[2]/div[2]/div[1]/div[6]/div[1]/text()",
  "dtMarkR": "",
  "dtActor": "/div[2]/div[2]/div[1]/div[3]/div[1]/a/text()",
  "dtActorR": "",
  "dtDirector": "/div[2]/div[2]/div[1]/div[2]/div[1]/a/text()",
  "dtDirectorR": "",
  "dtDesc": "/div[2]/div[2]/div[1]/div[1]/div[1]/p/text()",
  "dtDescR": "",
  "dtFromNode": "//div[contains(@class,'module-tab-item tab-item')]",
  "dtFromName": "/span/text()",
  "dtFromNameR": "",
  "dtUrlNode": "//div[contains(@class,'module-list sort-list tab-list his-tab-list')]",
  "dtUrlSubNode": "/div/div/a",
  "dtUrlId": "/@href",
  "dtUrlIdR": "",
  "dtUrlName": "/span/text()",
  "dtUrlNameR": "",
  "playUrl": "https://mozhatu.com/{playUrl}.html",
  "playUa": "",
  "searchUrl": "https://mozhatu.com/index.php/ajax/suggest?mid=1&wd={wd}&limit=10",
  "scVodNode": "json:list",
  "scVodName": "name",
  "scVodId": "id",
  "scVodIdR": "",
  "scVodImg": "pic",
  "scVodMark": ""
  }
