{
	"author": "baddychen",
	"ua": "",
	"homeUrl": "https://www.huya.com/g/",
	"cateNode": "//ul[@class='game-list clearfix']/li/a",
	"cateName": "/p/text()",
	"cateId": "/@href",
	"cateIdR": "https://www.huya.com/g/(\\S+)",
	"cateManual": {},
	"homeVodNode": "//ul[@class='live-list clearfix']/li",
	"homeVodName": "/a[contains(@class,'title')]/text()",
	"homeVodId": "/a[contains(@class,'video-info')]/@href",
	"homeVodIdR": "https://www.huya.com/(\\w+)",
	"homeVodImg": "/a[contains(@class,'video-info')]/img/@data-original",
	"homeVodImgR": "\\S+(http\\S+)",
	"homeVodMark": "concat(/a[contains(@class,'video-info')]/em/text(),'-',/a[contains(@class,'video-info')]/p/em/text(),'-','猫群首发751165954')",
	"cateUrl": "https://www.huya.com/g/{cateId}?page={catePg}",
	"cateVodNode": "//ul[@class='live-list clearfix']/li",
	"cateVodName": "/a[contains(@class,'title')]/text()",
	"cateVodId": "/a[contains(@class,'video-info')]/@href",
	"cateVodIdR": "https://www.huya.com/(\\w+)",
	"cateVodImg": "/a[contains(@class,'video-info')]/img/@data-original",
	"cateVodImgR": "\\S+(http\\S+)",
	"cateVodMark": "concat(/a[contains(@class,'video-info')]/em/text(),'-',/a[contains(@class,'video-info')]/p/em/text(),'-','猫群首发751165954')",
	"dtUrl": "https://www.huya.com/{vid}",
	"dtNode": "//body",
	"dtName": "//div[@class='host-info']/h1/text()",
	"dtNameR": "",
	"dtImg": "//div[@class='host-pic']/img/@src",
	"dtImgR": "\\S+(http\\S+)",
	"dtCate": "//span[@class='host-channel']/a[2]/text()",
	"dtArea": "//span[@class='host-channel']/a[1]/text()",
	"dtFromNode": "//h3[@class='host-name']",
	"dtFromName": "/text()",
	"dtFromNameR": "",
	"dtUrlNode": "//ul[@class='sidebar-icon-list']",
	"dtUrlSubNode": "/li[contains(@class,'allLive')]/a",
	"dtUrlId": "@eid_desc",
	"dtUrlIdR": "\\S+/(\\S+)",
	"dtUrlName": "/span/text()",
	"dtUrlNameR": "",
	"playUrl": "https://hd.huya.com/h5/liveshare/index.html?type=middlepage&rso=wap-live-share&lp={playUrl}",
	"playUa": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36",
	"searchUrl": "https://www.huya.com/search?hsk={wd}",
	"scVodNode": "//ul[@class='js-live-list']/li",
	"scVodName": "/a[@class='title new-clickstat']/@title",
	"scVodId": "/a[@class='title new-clickstat']/@href",
	"scVodIdR": "https://www.huya.com/(\\w+)",
	"scVodImg": "/a[@class='video-info new-clickstat']/img/@src",
	"scVodMark": ""
}