{
"sites": [
{"key":"csp_77"            ,"name":"🐞酷云七七","type":3,"api":"csp_Kunyu77","searchable":1,"quickSearch":1,"filterable":1},
{"key":"360_spider"        ,"name":"🐞360影视","api":"csp_SP360","type":3,"filterable":1,"quickSearch":1,"searchable":1,"ext":""},
{"key":"csp_CZSPP"         ,"name":"🐞厂长资源","type":3,"api":"csp_CZSPP","searchable":1,"quickSearch":1,"filterable":0},
{"key":"csp_Buka"          ,"name":"🐞真不卡","type":3,"api":"csp_Buka","searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_Kuaikan"       ,"name":"🐞快看影视","type":3,"api":"csp_Kuaikan","searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_ikan"          ,"name":"🐞爱看影视","type":3,"api":"csp_IKan","searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_DiDuan"        ,"name":"🐞低端影视","type":3,"api":"csp_DiDuan","searchable":1,"quickSearch":1,"filterable":0},
{"key":"csp_DY1990"        ,"name":"🐞九零影视","type":3,"api":"csp_DY1990","searchable":1,"quickSearch":1,"filterable":0},
{"key":"csp_Auete"         ,"name":"🐞Auete","type": 3,"api":"csp_Auete","searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_Cokemv"        ,"name":"🐞Cokemv","type":3,"api":"csp_Cokemv","searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_Bttoo"         ,"name":"🐞两个BT","type": 3,"api": "csp_Bttoo","searchable": 1,"quickSearch": 1,"filterable": 1},
{"key":"csp_xpath_libv"        ,"name":"🦋Libvio(XPF)","type":3,"api":"csp_XPathMacFilter","searchable":1,"quickSearch":1,"filterable":1,"ext":"https://liu673cn.github.io/box/sub/xpath/libv.json"},
{"key":"csp_xpath_zxzj2"       ,"name":"🦋在线之家(XPF)","type":3,"api":"csp_XPathFilter","searchable":1,"quickSearch":1,"filterable":1,"ext":"https://liu673cn.github.io/box/sub/xpath/zxzj2.json"},
{"key":"csp_xpath_lezhutv"     ,"name":"🦋乐猪TV(XP)","type":3,"api":"csp_XPathMac","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://liu673cn.github.io/box/sub/xpath/lezhutv.json"},
{"key":"csp_xpath_ddg"         ,"name":"🦋达达龟(XPF)","type":3,"api":"csp_XPathMacFilter","searchable":1,"quickSearch":1,"filterable":1,"ext":"https://liu673cn.github.io/box/sub/xpath/dadagui.json"},
{"key":"csp_xpath_jbb"         ,"name":"🦋剧白白(XPF)","type":3,"api":"csp_XPathMacFilter","searchable":1,"quickSearch":1,"filterable":1,"ext":"https://liu673cn.github.io/box/sub/xpath/jubaibai.json"},
{"key":"csp_xpath_jLgyy"       ,"name":"🦋蓝光影院(XPF)","type":3,"api":"csp_XPathFilter","searchable":1,"quickSearch":1,"filterable":1,"ext":"https://liu673cn.github.io/box/sub/xpath/lgyy.json"},
{"key":"csp_xpath_xiaoxiong"   ,"name":"🦋小熊影视(XPF)","type":3,"api":"csp_XPathFilter","searchable":1,"quickSearch":1,"filterable":1,"ext":"https://liu673cn.github.io/box/sub/xpath/xiaoxiong.json"},
{"key":"csp_xpath_doujiao"     ,"name":"🦋豆角影视(XP)","type": 3,"api": "csp_XPath","searchable": 1,"quickSearch": 1,"filterable": 1,"ext": "https://liu673cn.github.io/box/sub/xpath/doujiao.json"},
{"key":"csp_xpath_99ys"        ,"name":"🦋久久影视(XP)","type": 3,"api": "csp_XPath","searchable": 1,"quickSearch": 1,"filterable": 0,"ext": "https://liu673cn.github.io/box/sub/xpath/99ys.json"},
{"key":"csp_xpath_saohuo"      ,"name":"🦋骚火电影(XP)","type":3,"api":"csp_XPath","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://liu673cn.github.io/box/sub/xpath/saohuotv.json"},
{"key":"csp_xpath_nmys"        ,"name":"🦋农民影视(XPF)","type": 3,"api":"csp_XPathFilter","searchable":1,"quickSearch":1,"filterable":1,"ext":"https://liu673cn.github.io/box/sub/xpath/nmys2.json"},
{"key":"csp_xpath_xqmi"        ,"name":"🦋小 强 迷(XP)","type":3,"api":"csp_XPath","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://liu673cn.github.io/box/sub/xpath/xqmi.json"},
{"key":"csp_biubiu_小强迷"      ,"name":"🐛小 强 迷","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://liu673cn.github.io/box/sub/biubiu/小强迷.json"},
{"key":"csp_biubiu_tegou"      ,"name":"🐛特狗影视","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":1,"ext": "https://liu673cn.github.io/box/sub/biubiu/tegou.json"},
{"key":"csp_biubiu_真不卡zbk5"  ,"name":"🐛真不卡1(NS)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://liu673cn.github.io/box/sub/biubiu/真不卡zhenbuka3(ns).json"},
{"key":"csp_biubiu_真不卡cerrd" ,"name":"🐛真不卡2(NS)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://liu673cn.github.io/box/sub/biubiu/真不卡cerrd(ns).json"},
{"key":"csp_biubiu_奇优影院ns"  ,"name":"🐛奇优影院(NS)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://liu673cn.github.io/box/sub/biubiu/奇优影院(ns).json"},  
{"key":"csp_biubiu_黑狐影视ns"  ,"name":"🐛黑狐影视(NS)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://liu673cn.github.io/box/sub/biubiu/黑狐影视(ns).json"},
{"key":"csp_biubiu_影视工厂"    ,"name":"🐛影视工厂","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://liu673cn.github.io/box/sub/biubiu/影视工厂.json"},
{"key":"csp_biubiu_乐猪影视"    ,"name":"🐛乐猪影视2","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://liu673cn.github.io/box/sub/biubiu/乐猪影视.json"},
{"key":"csp_biubiu_蓝光影视"    ,"name":"🐛蓝光影视","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://liu673cn.github.io/box/sub/biubiu/蓝光影视.json"},
{"key":"csp_biubiu_双十电影"    ,"name":"🐛双十电影","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://liu673cn.github.io/box/sub/biubiu/双十电影.json"},
{"key":"csp_biubiu_韩剧佬"      ,"name":"🐛韩剧佬","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://liu673cn.github.io/box/sub/biubiu/韩剧佬.json"},  
{"key":"csp_biubiu_韩剧在线"    ,"name":"🐛韩剧在线","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://liu673cn.github.io/box/sub/biubiu/韩剧在线.json"},
{"key":"csp_biubiu_akmeiju"    ,"name":"🐛爱看美剧","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://liu673cn.github.io/box/sub/biubiu/akmeiju.json"},
{"key":"csp_appysv2_gotka"      ,"name":"🐌速播影视(v2)","type":3,"api":"csp_AppYsV2","searchable":1,"quickSearch":1,"filterable":1,"ext":"http://mkk.gotka.top/api.php/v1.vod"},
{"key":"csp_appysv2_9E03"       ,"name":"🐌9E03影视(v2)","type": 3,"api": "csp_AppYsV2","searchable": 1,"quickSearch": 1,"filterable": 1,"ext":"https://vod.9e03.com/lvdou_api.php/v1.vod"},
{"key":"csp_appysv2_独优影视"   ,"name":"🐌独优影视(v2)","type":3,"api":"csp_AppYsV2","searchable":1,"quickSearch":1,"filterable":1,"ext":"http://121.205.88.71:218/api.php/Chengcheng/vod/"},
{"key":"csp_appysv2_300看世界"  ,"name":"🐌300看世界(v2)","type":3,"api":"csp_AppYsV2","searchable":1,"quickSearch":1,"filterable":1,"ext":"https://300ys.xyz/mogai_api.php/v1.vod"},
{"key":"csp_appysv2_钟特影视"   ,"name":"🐌钟特影视(v2)","type":3,"api":"csp_AppYsV2","searchable":1,"quickSearch":1,"filterable":1,"ext":"https://app.zteys.com/api.php/v1.vod"},
{"key":"csp_appys_美剧虫"       ,"name":"🐌美剧虫(v1)","type":3,"api":"csp_AppYs","searchable":1,"quickSearch":1,"filterable":1,"ext":"https://meijuchong.com/api.php/v1.vod"},
{"key":"csp_BBB"           ,"name":"🐞哔哩哔哩","type": 3,"api": "csp_BBB","searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_Blixs"         ,"name":"🐞相声小品","type":3,"api":"csp_Blixs","searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_Bliyc"         ,"name":"🐞演唱会","type":3,"api":"csp_Bliyc","searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_Blidw"         ,"name":"🐞动物世界","type":3,"api":"csp_Blidw","searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_GitCafe"       ,"name":"🐞小纸条📵","type":3,"api":"csp_GitCafe","searchable":1,"quickSearch":1,"filterable":0},  
{"key":"csp_AliPanSou"     ,"name":"🐞云喵搜📵","type":3,"api":"csp_AliPanSou","searchable":1,"quickSearch":1,"filterable":0},
{"key":"push_agent"        ,"name":"🛴推送📵","type":3,"api":"csp_PushAgent","searchable":0,"quickSearch":0,"filterable":0},
//
{"key":"csp_xpath_huya","name":"🐯虎牙(XPF)","type":3,"api":"csp_XPathMacFilter","searchable":1,"quickSearch":1,"filterable":1,"ext":"https://liu673cn.github.io/box/sub/xpath/虎牙.json"},
{"key":"csp_xpath_huyam","name":"🐻虎牙M","type":3,"api":"csp_XPath","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://liu673cn.github.io/box/sub/xpath/huya.json"},
{"key":"csp_xpath_huyag","name":"🦊虎牙G","type":3,"api":"csp_XPathMacFilter","searchable":1,"quickSearch":1,"filterable":1,"ext":"https://liu673cn.github.io/box/sub/xpath/huya2.json"},
{"key":"csp_biubiu_斗鱼","name":"🐟斗鱼","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://liu673cn.github.io/box/sub/biubiu/斗鱼.json"},
{"key":"csp_xml___200121","name":"🐝200121","type":1,"api":"https://www.200121.com/api.php/provide/vod/","playUrl":"","searchable":1,"quickSearch":1},
{"key":"csp_xml___mac采集","name":"🐝苹果采集","type":1,"api":"http://107.150.5.146:39000/maccms10-main/api.php/provide/vod/at/xml","playUrl":"","searchable":1,"quickSearch":1},
{"key":"csp_xml___光速资源","name":"🐝光速资源","type":1,"api":"https://api.guangsuapi.com/api.php/provide/vod/","playUrl":"","searchable":1,"quickSearch":1},
{"key":"csp_xml___量子资源","name":"🐝量子资源","type":1,"api":"http://cj.lziapi.com/api.php/provide/vod/","playUrl":"","searchable":1,"quickSearch":1},
{"key":"csp_xml___xinlang","name":"🐝新浪资源","type":1,"api":"http://api.xinlangapi.com/xinlangapi.php/provide/vod/","playUrl":"","searchable":1,"quickSearch":1},
{"key":"csp_xpath_酷奇mv","name":"🎤酷奇MV","type":3,"api":"csp_XPath","searchable":0,"quickSearch":0,"filterable":0,"ext":"https://liu673cn.github.io/box/sub/xpath/酷奇MV.json"},
{"key":"csp_xml___8090","name":"💢8090资源"  ,"type":1,"api":"http://zy.yilans.net:8090/api.php/provide/vod/","playUrl":"","searchable":1,"quickSearch":1},
{"key":"csp_xml___小猫咪","name":"💢小 猫 咪"   ,"type":1,"api":"https://zy.xiaomaomi.cc/api.php/provide/vod/","playUrl":"","searchable":1,"quickSearch":1},
{"key":"csp_biubiu_小猫咪","name":"🐛小 猫 咪","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://liu673cn.github.io/box/sub/biubiu/小猫咪.json"}
],

"parses":[
{"name":"自动解析","type":3,"url":"Demo"},
{"name":"Json并发","type":2,"url":"Parallel"},
{"name":"Json轮询","type":2,"url":"Sequence"},
{"name":"线路1","type":1,"url":"http://27.124.4.42:4567/jhjson/ceshi.php?url=","ext":{"flag":["qiyi","qq","letv","sohu","youku","mgtv","bilibili","wasu","xigua","1905"]}},
{"name":"线路2","url": "http://81.71.48.249:4456/jsonc/293shipin.php?url=","type": 1,"i": "77",
"ext":{"flag":["qiyi","爱奇艺","奇艺","qq","腾讯","youku","优酷","pptv","PPTV","letv","乐视","bilibili","哔哩哔哩","哔哩","mgtv","芒果"]}},
{"name":"线路3","type":1,"url":"http://106.55.234.91:4433/?url=","ext":{"flag":["qiyi","qq","letv","sohu","youku","mgtv","bilibili","wasu","xigua","1905"]}},
{"name":"线路4","type": 1,"url": "http://81.71.48.249:4456/jsonc/longxia.php?url=","ext": {"flag": ["qq","qiyi","mgtv","youku","letv","sohu","xigua","1905"],"header": {"User-Agent": "Dart/2.14 (dart:io)"}}},
{"name":"线路5","type":1,"url":"https://jx.hfyrw.com/mao.go?url="},
{"name":"线路6","type":1,"url":"http://jiexi.mmhkj.xyz/home/api?type=ys&uid=4187535&key=enpstuBEJKLNPUXZ19&url="},
{"name":"线路7","type":1,"url":"https://app.okmedcos.com/4k/?url="},
{"name":"线路8","type":0,"url":"https://app.okmedcos.com/4k/?url=","ext":{"flag":["CL4K","qq","腾讯","pptv","PPTV"]}},
{"name":"线路9","type":1,"url":"https://jie.1z1.cc/api/?key=HdMmTMfyf1uTOQUL0b&url="},
{"name":"Pro","type": 1,"url": "http://api.vip123kan.vip/?url=","ext": {"flag": ["youku","优酷","mgtv","芒果","qq","腾讯","qiyi","爱奇艺","qq","奇艺"]}},
{"name":"parwix1","type":1,"url": "https://jx.parwix.com:4433/player/?url=","ext":{"flag":["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"]}},
{"name":"parwix2","type":1,"url": "https://jx.parwix.com:4433/player/analysis.php?v=","ext":{"flag":["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"]}},
{"name":"parwix3","type": 1,"url": "https://api.parwix.com:4433/analysis/json/?uid=1735&my=cejkmnuvyBEFINR056&url="},
{"name":"解析04","type": 1,"url": "http://jf.tcspvip.com:246/home/api?type=ys&uid=65404&key=bjoprtvyABGIMPXZ27&url="},
{"name":"播放呀","type": 1,"url": "https://jx.vk95.com/xx/?url="},
{"name":"剧好看","type": 1,"url": "https://www.mtosz.com/m3u8.php?url="},
{"name":"想看资源","type": 1,"url": "https://lyw28.com/m3u8/?url="},
{"name":"bilibili","type":1,"url":"https://vip.23at.cn/home/api?type=ys&uid=4883852&key=adfimsvxzDKNOVX389&url=","ext":{	"flag":["bilibili"]}},
{"name":"leduo","type":1,"url":"https://api.ldjx.cc/wp-api/getvodurl.php?token=1001&vid=","ext":{"flag":["leduo"]}},
{"name":"duoduozy2","type":1,"url":"https://a.dxzj88.com/jxjx/dd.php?url=","ext":{"flag":["duoduozy"]}},
{"name":"renrenmi1","type":1,"url":"https://jx.blbo.cc:4433/?url="},
{"name":"renrenmi2","type":1,"url":"https://a.dxzj88.com/jxrrm/jiami.php?url=","ext":{"flag":["rrm3u8"]}},
{"name":"renrenmi3","type":1,"url":"https://sz.dxzj88.com/jxrjrm/jiaomi.php?url=","ext":{"flag":["rrm3u8"]}},
{"name":"Pro2","type":1,"url":"https://vip.rongxingvr.top/api/?type=ys&key=JJEZkZIhzkA4cUtBfR&url=","ext":{"flag":["ltnb","rx","qiyi","爱奇艺","qq","奇艺","sohu","letv","youku","优酷","mgtv","芒果"]}},
{"name":"2","type":1,"url":"https://jx.mczdyw.com/xg.php?url=","ext":{"flag":["mgtv","芒果"]}},
{"name":"3","type":1,"url":"https://www.aiaine.com/api/?key=kVqmG5dAQ5dZTcECw8&url=","ext":{"flag":["youku","优酷","mgtv","芒果","qq","腾讯","qiyi","爱奇艺","qq","奇艺"]}},
{"name":"4","type":1,"url":"https://svip.rongxingvr.top/api/?key=niBgMGXVdCQhsmeEBK&url=","ext":{	"flag":["youku","优酷","mgtv","芒果","qq","腾讯","qiyi","爱奇艺","qq","奇艺"]}},
{"name":"8","type":1,"url":"https://app.iminna.com/jx/?url=","ext":{"flag":["youku","优酷","mgtv","芒果","qq","腾讯","qiyi","爱奇艺","qq","奇艺"]}},
{"name":"初心影视1","type":1,"url":"http://jhpc.manduhu.com/j1217.php?url=","ext":{"flag":["youku","优酷","qq","腾讯","mgtv","芒果"]}},
{"name":"飓风影院2","type":1,"url":"https://vvip.funsline.cn/api/?key=3xWfEoDf4V9p9Y20CR&url=","ext":{"flag":["ziqie","youku","优酷","qiyi","爱奇艺","奇艺","mgtv","芒果","qq","腾讯"]}},
{"name":"我爱电影网","type":1,"url":"https://jhpc.manduhu.com/j1217.php?url=","ext":{"flag":["qiyi","爱奇艺","奇艺","mgtv","芒果","youku","优酷","pptv","PPTV"]}},
{"name":"江湖解析","type":1,"url":"http://103.40.240.46/jh/?url=","ext":{	"flag":["renrenmi","qq","腾讯","youku","优酷","mgtv","芒果","xigua","西瓜"]}},
{"name":"王牌","type":1,"url":"https://za.kuanjv.com/?url=","ext":{"flag":["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","搜狐","sohu","letv","乐视","bilibili","哔哩哔哩","哔哩","xigua","西瓜"]}},
{"name":"我爱电影网","type":1,"url":"https://jhpc.manduhu.com/j1217.php?url=","ext":{"flag":["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","乐视","letv","PPTV","pptv","bilibili","哔哩哔哩","哔哩"]}},
{"name":"欢雨","type":1,"url":"http://www.youhuifuligou.com/json/?id=7&url=","ext":{"flag":["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","letv","乐视","xigua","西瓜"]}},
{"name":"hfyrw","type":1,"url":"https://json.hfyrw.com/mao.go?url=","ext":{"flag":["ltnb","renrenmi"]}},
{"name":"aiaine02","type":1,"url":"https://vip.aiaine.com/api/?key=8FN8gNAySnvJiMllxZ&url=","ext":{"flag":["ltnb","renrenmi","xfyun","miaoparty","miaoparty2","miaoparty3","longteng","xueren"]}},
{"name":"五一解析","type":1,"url":"https://json.5lp.net/json.php?url=","ext":{"flag":["ltnb","renrenmi","rx","rongxing"]}},
{"name":"RongXingVR","type":1,"url":"https://vip.rongxingvr.top/api/?key=JJEZkZIhzkA4cUtBfR&url=","ext":{"flag":["renrenmi","rx","rongxing","mgtv","芒果","bilibili","哔哩哔哩","哔哩"]}},
{"name":"jx165","type":1,"url":"https://ltjx.kuaixiao.vip/home/api?type=ys&uid=506916&key=dlmpwBHIKLMPQRVW23&url=","ext":{"flag":["ltnb"]}},
{"name":"J13","type":1,"url":"https://languangyingshiziyuan.1080zy.top/longtengzy.php/?url=","ext":{"flag":["ltnb"]}},
{"name":"xfyun云","type":1,"url":"https://vip.xfyun.one/home/api?type=ys&uid=2581923&key=ceijpquvBMOSUVXZ23&url=","ext":{"flag":["xfyun"]}},
{"name":"Wuduzy","type":1,"url":"https://aa.xkys.tv/json.php?url=","ext":{"flag":["wuduzy"]}},
{"name":"LTRX","type":1,"url":"https://svip.spchat.top/api/?type=ys&key=bKemW41JnxmQb4l67h&url=","ext":{"flag":["rx"]}},
{"name":"喵派对资源3","type":1,"url":"https://vip.aiaine.com/api/?key=fOWaGgFU45zlIjvbHI&url=","ext":{"flag":["ltnb","renrenmi"]}},
{"name":"喵派对资源2","type":1,"url":"https://svip.iremind.me/api/?key=A5Db8HF8c8FSIOR6R1&url=","ext":{"flag":["renrenmi","qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","bilibili","哔哩哔哩","哔哩","sohu"]}},
{"name":"leduotv","type":1,"url":"https://api.leduotv.com/wp-api/getvodurl.php?vid=","ext":{"flag":["leduo"]}},
{"name":"OJBK","type":0,"url":"https://jmwl.qd234.cn/v/?v=","ext":{"flag":["ltnb","renrenmi","rx","xfyun","muxm3u8","xigua","xueren","qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","bilibili","哔哩哔哩","哔哩","pptv","PPTV","sohu","letv"]}},
{"name":"M117","type":0,"url":"http://1.117.152.239:39000/?url="},
{"name":"zui","type":0,"url":"https://jx.zui.cm/?url=","ext":{"flag":["ltnb"]}},
{"name":"xuerenweb","type":0,"url":"https://s.2tu.uk/?url=","ext":{"flag":["xueren"]}},
{"name":"xuerenweb2","type":0,"url":"https://xrm3u8.qd234.cn/?url=","ext":{"flag":["xueren"]}},
{"name":"美剧虫","type":0,"url":"https://jx.daiguaji.com/?url=","ext":{"flag":["zijian"]}},
{"name":"miao","type":0,"url":"https://jx.58g8.com/1/?url=","ext":{"flag":["miaoparty"]}},
{"name":"web1","type":0,"url":"https://www.nxflv.com/?url=","ext":{"flag":["youku","优酷","mgtv","芒果","qq","腾讯","qiyi","爱奇艺","qq","奇艺","sohu","letv"]}},
{"name":"万能解析","type":0,"url":"https://vip.legendwhb.cn/m3u8.php?url=","ext":{"flag":["ltnb","renrenmi","qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","bilibili","哔哩哔哩","哔哩"]}},
{"name":"ltnb04","type":0,"url":"https://vip.bljiex.com/?v=","ext":{"flag":["ltnb"]}},
{"name":"ltnb02","type":0,"url":"https://jx.zui.cm/?url=","ext":{"flag":["ltnb"]}},
{"name":"CL4K01","type":0,"url":"https://ys.ling00.cn/CL4K/?url=","ext":{"flag":["CL4K","qq","腾讯"]}},
                {"name": "综合/B站","type": 1,"url": "https://vip.parwix.com:4433/player/?url="},
                {"name": "综合线路解析","type": 1,"url": "https://laisoyiba.com/mov/s/?sv=3&url="},
                {"name": "纯净/B站","type": 1,"url": "https://z1.m1907.cn/?jx="},
                {"name": "高速接口","type": 1,"url": "https://jsap.attakids.com/?url="},
                {"name": "OK解析","type": 1,"url": "https://okjx.cc/?url="},
                {"name": "OK解析2","type": 1,"url": "https://api.okjx.cc:3389/jx.php?url="},
                {"name": "夜幕","type": 1,"url": "https://www.yemu.xyz/?url="},
                {"name": "乐多资源","type": 1,"url": "https://api.leduotv.com/wp-api/ifr.php?isDp=1&vid="},
                {"name": "爱豆","type": 1,"url": "https://jx.aidouer.net/?url="},
                {"name": "虾米","type": 1,"url": "https://jx.xmflv.com/?url="},
                {"name": "M3U8.TV","type": 1,"url": "https://jx.m3u8.tv/jiexi/?url="},
                {"name": "人人迷","type": 1,"url": "https://jx.blbo.cc:4433/?url="},
                {"name": "全民","type": 1,"url": "https://jx.quanmingjiexi.com/?url="},
                {"name": "全民2","type": 1,"url": "https://chaxun.truechat365.com/?url="},
                {"name": "PPJ蓝光解析","type": 1,"url": "https://bf.ppjbk.cn/?url="},
                {"name": "PPJ解析","type": 1,"url": "https://jx.ppjbk.cn/?url="},
                {"name": "PPJ弹幕解析2","type": 1,"url": "https://bf.ppjbk.cn/bf/?url="},
                {"name": "m2090.","type": 1,"url": "https://m2090.com/?url="},
                {"name": "云解析","type": 1,"url": "https://jx.ppflv.com/?url="},
                {"name": "天翼解析","type": 1,"url": "https://www.qianyicp.com/vip/vip_g.php?url="},
                {"name": "百域","type": 1,"url": "https://jx.618g.com/?url="},
                {"name": "大幕","type": 1,"url": "https://jx.52damu.com/dmjx/jiexi.php?url="},
                {"name": "RDHK","type": 1,"url": "https://jx.rdhk.net/?v="},
                {"name": "淘电影","type": 1,"url": "https://jx.vodjx.top/vip/?url="},
                {"name": "维多","type": 1,"url": "https://jx.ivito.cn/?url="},
                {"name": "云端","type": 1,"url": "https://sb.5gseo.net/?url="},
                {"name": "七哥","type": 1,"url": "https://jx.mmkv.cn/tv.php?url="},
                {"name": "冰豆","type": 1,"url": "https://api.qianqi.net/vip/?url="},
                {"name": "迪奥","type": 1,"url": "https://123.1dior.cn/?url="},
                {"name": "CK","type": 1,"url": "https://www.ckplayer.vip/jiexi/?url="},
                {"name": "游艺","type": 1,"url": "https://api.u1o.net/?url="},
                {"name": "LE","type": 1,"url": "https://lecurl.cn/?url="},
                {"name": "ckmov","type": 1,"url": "https://www.ckmov.vip/api.php?url="},
                {"name": "playerjy/B站","type": 1,"url": "https://jx.playerjy.com/?url="},
                {"name": "ccyjjd","type": 1,"url": "https://ckmov.ccyjjd.com/ckmov/?url="},
                {"name": "爱豆","type": 1,"url": "https://jx.aidouer.net/?url="},
                {"name": "诺诺","type": 1,"url": "https://www.ckmov.com/?url="},
                {"name": "H8","type": 1,"url": "https://www.h8jx.com/jiexi.php?url="},
                {"name": "BL","type": 1,"url": "https://vip.bljiex.com/?v="},
                {"name": "解析la","type": 1,"url": "https://api.jiexi.la/?url="},
                {"name": "MUTV","type": 1,"url": "https://jiexi.janan.net/jiexi/?url="},
                {"name": "MAO","type": 1,"url": "https://www.mtosz.com/m3u8.php?url="},
                {"name": "老板","type": 1,"url": "https://vip.laobandq.com/jiexi.php?url="},
                {"name": "盘古","type": 1,"url": "https://www.pangujiexi.cc/jiexi.php?url="},
                {"name": "盖世","type": 1,"url": "https://www.gai4.com/?url="},
                {"name": "小蒋","type": 1,"url": "https://www.kpezp.cn/jlexi.php?url="},
                {"name": "YiTV","type": 1,"url": "https://jiexi.us/?url="},
                {"name": "星空","type": 1,"url": "http://60jx.com/?url="},
                {"name": "0523","type": 1,"url": "https://go.yh0523.cn/y.cy?url="},
                {"name": "17云","type": 1,"url": "https://www.1717yun.com/jx/ty.php?url="},
                {"name": "4K","type": 1,"url": "https://jx.4kdv.com/?url="},
                {"name": "云析","type": 1,"url": "https://jx.yparse.com/index.php?url="},
                {"name": "8090","type": 1,"url": "https://www.8090g.cn/?url="},
                {"name": "江湖","type": 1,"url": "https://api.jhdyw.vip/?url="},
                {"name": "诺讯","type": 1,"url": "https://www.nxflv.com/?url="},
                {"name": "PM","type": 1,"url": "https://www.playm3u8.cn/jiexi.php?url="},
                {"name": "奇米","type": 1,"url": "https://qimihe.com/?url="},
                {"name": "思云","type": 1,"url": "https://jx.ap2p.cn/?url="},
                {"name": "听乐","type": 1,"url": "https://jx.dj6u.com/?url="},
                {"name": "aijx","type": 1,"url": "https://jiexi.t7g.cn/?url="},
                {"name": "52","type": 1,"url": "https://vip.52jiexi.top/?url="},
                {"name": "黑米","type": 1,"url": "https://www.myxin.top/jx/api/?url="},
                {"name": "豪华啦","type": 1,"url": "https://api.lhh.la/vip/?url="},
                {"name": "凉城","type": 1,"url": "https://jx.mw0.cc/?url="},
                {"name": "33t","type": 1,"url": "https://www.33tn.cn/?url="},
                {"name": "180","type": 1,"url": "https://jx.000180.top/jx/?url="},
                {"name": "无名","type": 1,"url": "https://www.administratorw.com/video.php?url="},
                {"name": "黑云","type": 1,"url": "https://jiexi.380k.com/?url="},
                {"name": "九八","type": 1,"url": "https://jx.youyitv.com/?url="},
{"name": "解02","type": 1,"url": "https://json.5lp.net/json.php?url="},
{"name": "解03","type": 1,"url": "http://115.231.218.97:1314/api/?key=RwOSJUQyDGtD5K2qJY&url="},
{"name": "解04","type": 1,"url": "https://jhjx.kuanjv.com/newky/?url="},
{"name": "解05","type": 1,"url": "http://ts.yjhan.com:8090/api/?key=Y4GefMCIQJz23mc06R&url="},
{"name": "解06","type": 1,"url": "https://json.hfyrw.com/mao.go?url="},
{"name": "解08","type": 1,"url": "http://47.100.138.210:91/home/api?type=ys&uid=7593435&key=ehortuyAHMNQTWX457&url="},
{"name": "解09","type": 1,"url": "https://jb.vjiangbei.com/home/api?type=ys&uid=281459&key=dhlotwxzABCIJMT189&url="},
{"name": "解10","type": 1,"url": "https://jf.96ym.cn/api/?key=4tuNi0EjxTYFzJIN5r&url="},
{"name": "解11","type": 1,"url": "https://jb.vjiangbei.com/home/api?type=ys&uid=2219260&key=hlmnpqswHIKQRSX146&url="},
{"name": "解12","type": 1,"url": "http://jf.96ym.cn/api/?key=c9bUhQL7YsuL7y8oFz&url="},
{"name": "解13","type": 1,"url": "http://42.157.128.85:880/analysis/json/?uid=2245&my=chorsvzDIKVWX34789&url="},
{"name": "解14","type": 1,"url": "http://23.224.174.74:5577/home/api?type=ys&uid=19722&key=aghknrsvxCDEGNRSUZ&url="},
{"name": "解15","type": 1,"url": "https://jx.7kjx.com/?url="},
{"name": "解16","type": 1,"url": "http://jiexi.kudian6.com/pzjx/zz.php?url="},
{"name": "解17","type": 1,"url": "http://47.100.138.210:91/home/api?type=ys&uid=243653&key=kqswxyABGHKLQSV127&url="},
{"name": "解18","type": 1,"url": "https://xt.gbxy.net.cn/api/?key=7gAmfK5typSVsg2Qnr&url="},
{"name": "解19","type": 1,"url": "https://svip.renrenmi.cc:2222/api/?key=nn4j8rukPXSVzR78E9&url="},
{"name": "解20","type": 1,"url": "https://kuba.renrenmi.cc:2266/api/?key=1PhqM8xRCbmfgwmcE2&url="},
{"name": "解21","type": 1,"url": "http://www.youhuifuligou.com/json/?id=1&url="},
{"name": "解22","type": 1,"url": "https://dd.mouliuk.com/home/api?type=ys&uid=12293&key=acfhkovxzDEIMPWX29&url="},
{"name": "解23","type": 1,"url": "https://vip.byteamone.cn/api/?key=vpO0packXeAp4XYCnA&url="},
{"name": "解24","type": 1,"url": "https://sbsb.i8k.cc/?url="},
{"name": "解25","type": 1,"url": "http://gq.bywdtk.cn/?url="},
{"name": "解26","type": 1,"url": "https://balabala.yatongle.com/api/?key=RuHZpg9zxigiLZRIyl&url="},
{"name": "解27","type": 1,"url": "http://jx.ledu8.cn/api/?key=P8QSgO61p1MpHV2ALn&url="},
{"name": "解28","type": 1,"url": "https://jb.vjiangbei.com/home/api?type=ys&uid=281459&key=cfnoprCDJKLNPQTY34&url="},
{"name": "解29","type": 1,"url": "http://47.100.138.210:91/home/api?type=ys&uid=1947441&key=bcfgjmuwCEORSVX237&url="},
{"name": "解30","type": 1,"url": "http://a.dxzj88.com/jhjson/?url="},
{"name": "解31","type": 1,"url": "https://svip.spchat.top/api/?key=SAl7tLs3Zzu5alSNtz&url="},
{"name": "解32","type": 1,"url": "https://vip.kpjx.cc/api/?key=3sKKYzWSxLmX1hnsMs&url="},
{"name": "解33","type": 1,"url": "http://47.100.138.210:91/home/api?type=ys&uid=1947441&key=bcfgjmuwCEORSVX237&url="},
{"name": "解34","type": 1,"url": "http://jf.jisutuku.top/api/?key=RHjXcjUTkyZnfWx9u4&url="},
{"name": "解35","type": 1,"url": "http://47.100.138.210:91/home/api?type=ys&uid=243653&key=kqswxyABGHKLQSV127&url="},
{"name": "解36","type": 1,"url": "http://42.157.128.85:880/analysis/json/?uid=2245&my=cdnouwxBHLMQSUVWZ1&url="},
{"name": "解37","type": 1,"url": "https://vip.rongxingvr.top/api/?key=JJEZkZIhzkA4cUtBfR&url="},
{"name": "解38","type": 1,"url": "https://jx.zhanlangbu.com/json.php/?url="},
{"name": "解39","type": 1,"url": "https://api.zakkpa.com:8888/analysis/json/?uid=39&my=ehklrtxzAFKLMNUXY2&url="},
{"name": "解40","type": 1,"url": "https://api.zakkpa.com:8888/analysis/json/?uid=39&my=bdfinvyBCDEJKUY089&url="},
{"name": "解41","type": 1,"url": "https://jx.kujiexi.net/m3u8.php?url="},
{"name": "解42","type": 1,"url": "http://jx.ykyunbo.com/m3u8.php?url="},
{"name": "解43","type": 1,"url": "https://player.aibozyplayer.com/m3u8/?url="},
{"name": "解44","type": 1,"url": "https://player.sewozyplayer.com/m3u8/?url="},
{"name": "解45","type": 1,"url": "https://help.siwazywcdn2.com:5278/m3u8.php?url="},
{"name": "解46","type": 1,"url": "https://player.leyuzy.net/?url="},
{"name": "解47","type": 1,"url": "https://api.xiusebf.com/m3u8/?url="},
{"name": "解48","type": 1,"url": "https://mgm3u8-player.com/player/DPm3u8.php?url="},
{"name": "解49","type": 1,"url": "https://player.77lehuo.com/aliplayer/?url="},
{"name": "解50","type": 1,"url": "https://jx.ykyunbo.com/m3u8.php?url="},
{"name": "解51","type": 1,"url": "http://www.ikukk.com/?url="},
{"name": "解52","type": 1,"url": "https://jx.xmflv.com/?url="},
{"name": "解53","type": 1,"url": "https://www.8090g.cn/?url="},
{"name": "解54","type": 1,"url": "http://api.diliktv.xyz/vip/jx.php?url="},
{"name": "解55","type": 1,"url": "https://nbjx.vip/?url="},
{"name": "解56","type": 1,"url": "https://api.okjx.cc:3389/jx.php?url="},
{"name": "解57","type": 1,"url": "https://www.xymav.com/?url="},
{"name": "解58","type": 1,"url": "https://9kjx.com/?url="},
{"name": "解59","type": 1,"url": "https://dp.fqplayer.com/dplayer/?url="},
{"name": "解60","type": 1,"url": "https://jx.blbo.cc:4433/?url="},
{"name": "解61","type": 1,"url": "https://api.iztyy.com/jiexi/?url="},
{"name": "解62","type": 1,"url": "https://www.91jxs.com/jiexi/?url="},
{"name": "解63","type": 1,"url": "http://vip.26db.cn/c/?url="},
{"name": "解64","type": 1,"url": "http://vip.26db.cn/f/?url="},
{"name": "解65","type": 1,"url": "http://vip.26db.cn/a/?url="},
{"name": "解66","type": 1,"url": "http://okjx.cc/?url="},
{"name": "解67","type": 1,"url": "http://jx.xdiaosi.com/?url="},
{"name": "解68","type": 1,"url": "http://jx.rdhk.net/?url="},
{"name": "解69","type": 1,"url": "https://ckmov.ccyjjd.com/ckmov/?url="},
{"name": "解70","type": 1,"url": "https://okjx.cc/?url="},
{"name": "解71","type": 1,"url": "https://www.nxflv.com/?url="},
{"name": "解72","type": 1,"url": "http://gq.bywdtk.cn/?url="},
{"name": "解73","type": 1,"url": "https://api.zakkpa.com:8888/analysis/json/?uid=91&my=gjksuvCHIJLRS01268&url="},
{"name": "解74","type": 1,"url": "http://jx.ledu8.cn/api/?key=P8QSgO61p1MpHV2ALn&url="},
{"name": "解75","type": 1,"url": "https://json.legendwhb.cn/json.php/?url="},
{"name": "解76","type": 1,"url": "http://14.17.115.200:520/json.php?id=6e5LaYyU5JLs9aRawyGKwPkH7ZFr701z&url="},
{"name": "解77","type": 1,"url": "http://newjiexi.gotto.top/yun_apib.php/?url="},
{"name": "解78","type": 1,"url": "http://vipjh.chunbaotaiji.com/?url="},
{"name": "解79","type": 1,"url": "https://jhjx.ptygx.com/xttyjx.php/?url="}
],
"lives": [
{
"group": "redirect",
"channels": [
{
"name": "redirect",
"urls": [
"proxy://do=live&type=txt&ext=aHR0cHM6Ly9rZHMyLmNvZGluZy5uZXQvcC9rL2Qvay9naXQvcmF3L21hc3Rlci9tYW9saXZlLnR4dA=="
]}]}],

"spider":"https://liu673cn.github.io/box/jar/custom_spider.jar;md5;B45C4ECEA82BFE22D3E8B86A69E04407",

"flags":["youku","qq","iqiyi","qiyi","letv","sohu","tudou","pptv","mgtv","wasu","bilibili","renrenmi"],
"ijk":[
{"group":"软解码","options":[
{"category":4,"name":"opensles","value":"0"},
{"category":4,"name":"overlay-format","value":"842225234"},
{"category":4,"name":"framedrop","value":"1"},
{"category":4,"name":"soundtouch","value":"1"},
{"category":4,"name":"start-on-prepared","value":"1"},
{"category":1,"name":"http-detect-range-support","value":"0"},
{"category":1,"name":"fflags","value":"fastseek"},
{"category":2,"name":"skip_loop_filter","value":"48"},
{"category":4,"name":"reconnect","value":"1"},
{"category":4,"name":"enable-accurate-seek","value":"0"},
{"category":4,"name":"mediacodec","value":"0"},
{"category":4,"name":"mediacodec-auto-rotate","value":"0"},
{"category":4,"name":"mediacodec-handle-resolution-change","value":"0"},
{"category":4,"name":"mediacodec-hevc","value":"0"},
{"category":1,"name":"dns_cache_timeout","value":"600000000"}]},
{"group":"硬解码","options":[
{"category":4,"name":"opensles","value":"0"},
{"category":4,"name":"overlay-format","value":"842225234"},
{"category":4,"name":"framedrop","value":"1"},
{"category":4,"name":"soundtouch","value":"1"},
{"category":4,"name":"start-on-prepared","value":"1"},
{"category":1,"name":"http-detect-range-support","value":"0"},
{"category":1,"name":"fflags","value":"fastseek"},
{"category":2,"name":"skip_loop_filter","value":"48"},
{"category":4,"name":"reconnect","value":"1"},
{"category":4,"name":"enable-accurate-seek","value":"0"},
{"category":4,"name":"mediacodec","value":"1"},
{"category":4,"name":"mediacodec-auto-rotate","value":"1"},
{"category":4,"name":"mediacodec-handle-resolution-change","value":"1"},
{"category":4,"name":"mediacodec-hevc","value":"1"},
{"category":1,"name":"dns_cache_timeout","value":"600000000"}]}],
"ads":["mimg.0c1q0l.cn","www.googletagmanager.com","www.google-analytics.com","mc.usihnbcq.cn","mg.g1mm3d.cn","mscs.svaeuzh.cn","cnzz.hhttm.top","tp.vinuxhome.com","cnzz.mmstat.com","www.baihuillq.com","s23.cnzz.com","z3.cnzz.com","c.cnzz.com","stj.v1vo.top","z12.cnzz.com","img.mosflower.cn","tips.gamevvip.com","ehwe.yhdtns.com","xdn.cqqc3.com","www.jixunkyy.cn","sp.chemacid.cn","hm.baidu.com","s9.cnzz.com","z6.cnzz.com","um.cavuc.com","mav.mavuz.com","wofwk.aoidf3.com","z5.cnzz.com","xc.hubeijieshikj.cn","tj.tianwenhu.com","xg.gars57.cn","k.jinxiuzhilv.com","cdn.bootcss.com","ppl.xunzhuo123.com","xomk.jiangjunmh.top","img.xunzhuo123.com","z1.cnzz.com","s13.cnzz.com","xg.huataisangao.cn","z7.cnzz.com","xg.huataisangao.cn","z2.cnzz.com","s96.cnzz.com","q11.cnzz.com","thy.dacedsfa.cn","xg.whsbpw.cn","s19.cnzz.com","z8.cnzz.com","s4.cnzz.com","f5w.as12df.top","ae01.alicdn.com","www.92424.cn","k.wudejia.com","vivovip.mmszxc.top","qiu.xixiqiu.com","cdnjs.hnfenxun.com","cms.qdwght.com"]
}
