{
  "name": "骚火电影",
  "url": "https://shdy2.com",
  "User": "空",
  "shouye": "1",
  "fenlei": "国产剧$/list/20-#电影$/list/1-#电视剧$/list/2-#动漫$/list/3-#美剧$/list/23-#喜剧片$/list/6-#爱情片$/list/7-#恐怖片$/list/8-#动作片$/list/9-#科幻片$/list/10-#战争片$/list/11-#犯罪片$/list/12-#动画片$/list/13-#奇幻片$/list/14-#剧情片$/list/15-#冒险片$/list/16-#悬疑片$/list/17-#惊悚片$/list/18-#其它片$/list/19-#香港剧$/list/21-#韩剧$/list/22-#日剧$/list/24-#英剧$/list/25-#台剧$/list/26-#其它剧$/list/27-",
  "houzhui": ".html",
  "shifouercijiequ": "0",
  "jiequqian": "空",
  "jiequhou": "空",
  "jiequshuzuqian": "class=\"v_img\">",
  "jiequshuzuhou": "</p>",
  "tupianqian": "data-original=\"",
  "tupianhou": "\"",
  "biaotiqian": "title=\"",
  "biaotihou": "\"",
  "lianjieqian": "href=\"",
  "lianjiehou": "\"",
  "sousuoqian": "/search.php?searchword=",
  "sousuohou": "",
  "sousuohouzhui": "/movie/",
  "ssmoshi": "1",
  "sousuoshifouercijiequ": "0",
  "jspic": "pic",
  "jsname": "name",
  "jsid": "id",
  "ssjiequqian": "空",
  "ssjiequhou": "空",
  "ssjiequshuzuqian": "<div class=\"v_img\">",
  "ssjiequshuzuhou": "<div class=\"v_note\">",
  "sstupianqian": "data-original=\"",
  "sstupianhou": "\"",
  "ssbiaotiqian": "title=\"",
  "ssbiaotihou": "\"",
  "sslianjieqian": "href=\"",
  "sslianjiehou": "\"",
  "bfshifouercijiequ": "0",
  "bfjiequqian": "空",
  "bfjiequhou": "空",
  "bfjiequshuzuqian": "id=\"play_link\"",
  "bfjiequshuzuhou": "</ul>",
  "zhuangtaiqian": "class=\"v_note\">",
  "zhuangtaihou": "</div>",
  "daoyanqian": "导演：",
  "daoyanhou": "/ 主演",
  "zhuyanqian": "主演：",
  "zhuyanhou": "</p>",
  "juqingqian": "class=\"p_txt show_part\">",
  "juqinghou": "<br",
  "bfyshifouercijiequ": "0",
  "bfyjiequqian": "空",
  "bfyjiequhou": "空",
  "bfyjiequshuzuqian": "<a",
  "bfyjiequshuzuhou": "/a>",
  "bfbiaotiqian": ">",
  "bfbiaotihou": "<",
  "bflianjieqian": "href=\"",
  "bflianjiehou": "\""
}
