{
    "author": "春风",
    "ua": "",
    "homeUrl": "https://www.bttwoo.com",
    "dcVipFlag": "true",
    "dcPlayUrl": "true",
    "cateManual": {
        "最新电影": "new-movie",
        "热门电影": "hot",
        "本月热门": "hot-month",
        "高分电影": "gf",
        "国产剧": "zgjun",
        "美剧": "meiju",
        "日韩剧": "jpsrtv",
        "喜剧": "movie_bt_tags/xiju",
        "爱情": "movie_bt_tags/aiqing",
        "冒险": "movie_bt_tags/adt",
        "动作": "movie_bt_tags/at",
        "奇幻": "movie_bt_tags/qihuan",
        "悬疑": "movie_bt_tags/xuanni",
        "惊悚": "movie_bt_tags/jingsong",
        "武侠": "movie_bt_tags/wuxia",
        "国漫": "movie_bt/movie_bt_cat/dl/movie_bt_tags/donghua",
        "日漫": "movie_bt/movie_bt_cat/rb/movie_bt_tags/donghua",
        "美漫": "movie_bt/movie_bt_cat/mg/movie_bt_tags/donghua"
    },
    "homeVodNode": "//div[contains(@class,'bt_img')]/ul/li",
    "homeVodName": "/h3/a/text()",
    "homeVodId": "/a/@href",
    "homeVodIdR": "https://www.bttwoo.com/(\\S+).html",
    "homeVodImg": "/a/img/@data-original",
    "homeVodImgR": "",
    "homeVodMark": "",
    "cateUrl": "https://www.bttwoo.com/{cateId}/page/{catePg}",
    "cateVodNode": "//div[contains(@class,'bt_img')]/ul/li",
    "cateVodName": "/h3/a/text()",
    "cateVodId": "/a/@href",
    "cateVodIdR": "https://www.bttwoo.com/(\\S+).html",
    "cateVodImg": "/a/img/@data-original",
    "cateVodImgR": "",
    "cateVodMark": "",
    "dtUrl": "https://www.bttwoo.com/{vid}.html",
    "dtNode": "//body",
    "dtName": "//h1/text()",
    "dtNameR": "",
    "dtImg": "//div[@class='dyimg fl']/img/@src",
    "dtImgR": "",
    "dtCate": "//li[contains(text(), '类型')]/child::text()",
    "dtCateR": "",
    "dtYear": "//li[contains(text(), '年份')]/child::text()",
    "dtYearR": "",
    "dtArea": "//li[contains(text(), '地区')]/child::text()",
    "dtAreaR": "",
    "dtDirector": "//li[contains(text(), '导演')]/child::text()",
    "dtDirectorR": "",
    "dtActor": "//li[contains(text(), '主演')]/child::text()",
    "dtActorR": "",
    "dtDesc": "concat(//div[@class='yp_context']/text(),//div[@class='yp_context']/p/text())",
    "dtDescR": "",
    "dtFromNode": "//div[@class='mi_paly_box']/div/div[@class='ypxingq_t']",
    "dtFromName": "/text()",
    "dtFromNameR": "",
    "dtUrlNode": "//div[@class='paly_list_btn']",
    "dtUrlSubNode": "/a",
    "dtUrlId": "@href",
    "dtUrlIdR": "https://www.bttwoo.com/v_play/(\\S+).html",
    "dtUrlName": "/text()",
    "dtUrlNameR": "",
    "playUrl": "https://www.bttwoo.com/v_play/{playUrl}.html",
    "playUa": "",
    "searchUrl": "https://www.bttwoo.com/xssearch?q={wd}",
    "scVodNode": "//div[contains(@class,'search_list')]/ul/li",
    "scVodName": "/h3/a/text()",
    "scVodId": "/@href",
    "scVodIdR": "https://www.bttwoo.com/(\\S+).html",
    "scVodImg": "//img/@data-original",
    "scVodMark": ""
}