{
  "author":"takagen99",
  "ua": "",
  "homeUrl": "https://www.pianba.tv",
  "dcVipFlag": "true",
  "pCfgJs": "https://www.pianba.tv/static/js/playerconfig.js",
  "pCfgJsR": "[\\W|\\S|.]*?MacPlayerConfig.player_list[\\W|\\S|.]*?=([\\W|\\S|.]*?),MacPlayerConfig.downer_list",
  "dcShow2Vip": {},
  "dcPlayUrl": "true",
  "cateNode": "//ul[contains(@class,'stui-header__menu')]/li/a[contains(@href, 'sort') and not(contains(@href,'label'))]",
  "cateName": "/text()",
  "cateId": "/@href",
  "cateIdR": "/sort/(\\w+).html",
  "cateManual": {},
  "homeVodNode": "//div[contains(@class, 'stui-pannel__bd')]//ul[contains(@class,'stui-vodlist')]/li//a[contains(@class,'stui-vodlist__thumb')]",
  "homeVodName": "/@title",
  "homeVodId": "/@href",
  "homeVodIdR": "/html/(\\w+).html",
  "homeVodImg": "/@data-original",
  "homeVodImgR": "\\S+(http\\S+)",
  "homeVodMark": "/span[contains(@class,'pic-text')]/text()",
  "cateUrl": "https://www.pianba.tv/sort/{cateId}-{catePg}.html",
  "cateVodNode": "//ul[contains(@class,'stui-vodlist')]//li//a[contains(@class,'stui-vodlist__thumb')]",
  "cateVodName": "/@title",
  "cateVodId": "/@href",
  "cateVodIdR": "/html/(\\w+).html",
  "cateVodImg": "/@data-original",
  "cateVodImgR": "\\S+(http\\S+)",
  "cateVodMark": "/span[contains(@class,'pic-text')]/text()",
  "dtUrl": "https://www.pianba.tv/html/{vid}.html",
  "dtNode": "//div[@class='stui-content']",
  "dtName": "//div[@class='stui-content__detail']/h1/text()",
  "dtNameR": "",
  "dtImg": "//div[@class='stui-content__thumb']/a/img/@data-original",
  "dtImgR": "\\S+(http\\S+)",
  "dtYear": "//div[@class='stui-content__detail']//span[contains(@class,'data2') and contains(text(), '年份')]/following-sibling::*/text()",
  "dtYearR": "",
  "dtCate": "//div[@class='stui-content__detail']//span[contains(@class,'data2') and contains(text(), '类型')]/following-sibling::*/text()",
  "dtCateR": "",
  "dtArea": "//div[@class='stui-content__detail']//span[contains(@class,'data2') and contains(text(), '地区')]/following-sibling::*/text()",
  "dtAreaR": "",
  "dtDirector": "//div[@class='stui-content__detail']//span[contains(@class,'data2') and contains(text(), '导演')]/following-sibling::*/text()",
  "dtDirectorR": "",
  "dtActor": "//div[@class='stui-content__detail']//span[contains(@class,'data2') and contains(text(), '演员')]/following-sibling::*/text()",
  "dtActorR": "",
  "dtDesc": "//div[@class='stui-content__detail']//span[contains(@class,'data2') and contains(text(), '简介')]/parent::text()",
  "dtDescR": "",
  "dtFromNode": "//div[contains(@class,'stui-vodlist__head')]/span",
  "dtFromName": "/text()",
  "dtFromNameR": "",
  "dtUrlNode": "//ul[contains(@class,'stui-content__playlist')]",
  "dtUrlSubNode": "//li/a",
  "dtUrlId": "/@href",
  "dtUrlIdR": "/yun/(\\S+).html",
  "dtUrlName": "/text()",
  "dtUrlNameR": "",
  "playUrl": "https://www.pianba.tv/yun/{playUrl}.html",
  "playUa": "",
  "searchUrl": "https://www.pianba.tv/index.php/ajax/suggest?mid=1&wd={wd}&limit=10",
  "scVodNode": "json:list",
  "scVodName": "name",
  "scVodId": "id",
  "scVodIdR": "",
  "scVodImg": "pic",
  "scVodMark": ""
}
