{
  "ua": "",
   "homeUrl": "https://www.31kan.vip/",
//"dcVipFlag": "true",
//"pCfgJs": "https://gimytv.com//static/js/playerconfig.js",
//"pCfgJsR": "[\\W|\\S|.]*?MacPlayerConfig.player_list[\\W|\\S|.]*?=([\\W|\\S|.]*?),MacPlayerConfig.downer_list",
//"dcShow2Vip": {},
//"dcPlayUrl": "true",
  "cateManual": {"电影": "1", "电视剧": "2", "综艺": "3", "动漫": "4", "少儿": "33"},
  "homeVodNode": "//ul[contains(@class, 'myui-vodlist clearfix')]/li/div",
  "homeVodName":"/a[contains(@class, 'myui-vodlist__thumb')]/@title",
  "homeVodId": "/a[contains(@class, 'myui-vodlist__thumb')]/@href",
  "homeVodIdR": "/31kan/(\\S+).html",
  "homeVodImg": "/a[contains(@class, 'myui-vodlist__thumb')]/@data-original",
  "homeVodMark": "",
  "cateUrl": "https://www.31kan.vip/vodshow/{cateId}--------{catePg}---.html",
  "cateVodNode":  "//ul[contains(@class, 'myui-vodlist clearfix')]/li/div",
  "cateVodName": "/a[contains(@class, 'myui-vodlist__thumb')]/@title",
  "cateVodId": "/a[contains(@class, 'myui-vodlist__thumb')]/@href",
  "cateVodIdR": "/31kan/(\\S+).html",
  "cateVodImg": "/a[contains(@class, 'myui-vodlist__thumb')]/@data-original",
  "cateVodMark": "",
  "dtUrl": "https://www.31kan.vip/31kan/{vid}.html",
  "dtNode": "//div[contains(@class,'myui-content__thumb')]",
  "dtName": "/a/@title",
  "dtImg":"/a/img/@data-original",
 "dtFromNode": "//div[contains(@class,'myui-panel_hd')]/div/ul[contains(@class,'nav nav-tabs active')]/li/a",
 "dtFromName": "/text()",
  "dtUrlNode": "//ul[contains(@class,'myui-content__list')]",
  "dtUrlSubNode": "/li/a",
  "dtUrlId": "@href",
  "dtUrlIdR": "/play/(\\S+).html",
  "dtUrlName": "/text()",
  "playUrl": "https://www.31kan.vip/play/{playUrl}.html",
 "searchUrl": "https://www.31kan.vip/index.php/ajax/suggest?mid=1&wd={wd}",
  "scVodNode": "json:list",
  "scVodName": "name",
  "scVodId": "id",
  "scVodIdR": "",
  "scVodImg": "pic",
  "scVodMark": ""
}