name: Sync all branches
on:
  workflow_dispatch:
jobs:
  update_external_airflow_fork:
    runs-on: ubuntu-latest
      steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          upstream_repository: liu673cn/box
          target_repository: woshishiq1/mao
          upstream_branch: master
          target_branch: master
          force: true
          tags: true
